version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_default
    ports:
      - "5432:5432"
    networks:
      - bal-network

  web1:
    build: ./nginx_image
    container_name: web1
    ports:
      - "8082:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - bal-network

  web2:
    build: ./nginx_image
    container_name: web2
    ports:
      - "8083:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - bal-network

  haproxy:
    build: ./haproxy_image
    container_name: haproxy
    ports:
      - "8080:80"
    networks:
      - bal-network

  nginx:
    build: ./nginx_image
    container_name: nginx
    ports:
      - "8081:80"
    networks:
      - bal-network

networks:
  bal-network:
    driver: bridge
